version: "3"

services:
  zammad-api-wrapper:
    build:
      context: .
    container_name: zammad-api-wrapper
    image: zammad-api-wrapper
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - API_BASE_URL=http://77.68.114.90:8080/api/v1
      - PORT=3000
      - SERVER_ROOT=http://77.68.114.90:5000
    ports:
      - "5000:3000"
